

services:
  nats:
    image: nats:2.11
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -m 8222
    restart: always
  
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    restart: always
  
  influxdb-init:
    image: influxdb:2
    depends_on:
      - influxdb
    restart: "no"
    entrypoint: ["/bin/bash"]
    command: >
      -c '
      echo "Waiting for InfluxDB to be ready...";
      for i in {1..30}; do
        curl -s http://influxdb:8086/ping > /dev/null && break || sleep 2;
      done;
      echo "Creating aggregated_data bucket...";
      influx bucket create --name ${INFLUXDB_AGGREGATED_BUCKET} --org ${INFLUXDB_ORG} --token ${INFLUXDB_ADMIN_TOKEN} --host http://influxdb:8086;
      echo "InfluxDB initialization completed.";
      '
    environment:
      - INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_AGGREGATED_BUCKET=${INFLUXDB_AGGREGATED_BUCKET}
  
  sensors:
    build: ./sensors
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    restart: always
  consumer:
    build: ./consumer
    depends_on:
      - nats
      - influxdb
    environment:
      - NATS_URL=nats://nats:4222
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - TEMP_ALERT_THRESHOLD=${TEMP_ALERT_THRESHOLD}
      - ALERT_STATE_FILE=/app/data/alert_state.json 
    volumes:
      - consumer-data:/app/data
    restart: always
  
  alert:
    build: ./alert
    volumes:
      - ./alert/config:/app/config:ro
    environment:
      - CONFIG_PATH=/app/config/email_config.json
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    restart: on-failure
  processor:
    build: ./processor
    depends_on:
      - nats
      - influxdb
      - influxdb-init
    environment:
      - NATS_URL=nats://nats:4222
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_SOURCE_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TARGET_BUCKET=${INFLUXDB_AGGREGATED_BUCKET}
      - AGGREGATION_INTERVAL=30s
    restart: always
  historian:
    build: ./historian
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - influxdb-init
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_RAW_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_AGGREGATED_BUCKET=${INFLUXDB_AGGREGATED_BUCKET}
    restart: always

volumes:
  influxdb2-data:
  influxdb2-config:
  consumer-data:
